version: "3.2"
services:
  frontend:
    container_name: frontend
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./src:/code
      - node_modules:/code/node_modules
    ports:
      - "3000:3000"
    entrypoint: /bin/bash -c "npm start"

  backend:
    container_name: backend
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code
    ports:
        - "8000:8000"
    entrypoint: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
    node_modules: